server:
  port: 8703

spring:
  application:
    name: bazl-dna-turbine     

turbine: 
  combine-host-port: true
  app-config: bazl-dna-system,bazl-dna-zuul,bazl-dna-files,bazl-dna-gateway,bazl-dna-monitor
  aggregator: 
    cluster-config: default
  cluster-name-expression:  new String("default")
  
logging:
  config: classpath:logback-spring.xml