server: 
  port: 8705
spring:
  application:
    name: bazl-dna-files
  servlet:
    multipart:
      enabled: true  
      max-file-size: 30MB
      max-request-size: 30MB    

logging:
  config: classpath:logback-spring.xml  
  