server:
  port: 8700

spring: 
  profiles:
    active: dev
  application:
    name: bazl-dna-eureka  
  security: 
    user: 
      name: root 
      password: root
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
logging:
  config: classpath:logback-spring.xml
