spring:
  datasource:
    #mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dnacloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 1234
    
    #postgres
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/dnacloud
    #username: postgres
    #password: 1234
    
  jpa: 
    hibernate:
      ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
      
  redis:
    database: 1

  data:
    redis:
      repositories:
        enabled: false
        
# FastDFS
fdfs:
  connect-timeout: 60
  so-timeout: 1500
  tracker-list: 192.168.101.130:22122
  thumb-image:
    height: 150
    width: 150
  web-server-url: http://192.168.101.130
  ip: 192.168.101.130
  port: 22
  user: root
  password: root
  storage:
    # 用于文件路径展示
    path: /data/fastdfs-storage/data
  pool:
    #连接池最大数量
    max-total: 200
    #每个tracker地址的最大连接数
    max-total-per-key: 50
    #连接耗尽时等待获取连接的最大毫秒数
    max-wait-millis: 5000
    