spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource

      #mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dnatask?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: root
      password: 1234
      
      #postgres
      #driver-class-name: org.postgresql.Driver
      #url: jdbc:postgresql://localhost:5432/dnatask
      #username: postgres
      #password: 1234
    
  jpa: 
    hibernate:
      ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    
  redis:
    database: 1
  
  data:
    redis:
      repositories:
        enabled: false

#服务器配置  
servers:
  deploy: true
  path: /usr/local/tomcat/dnacloud
  version: 1.0.0-SNAPSHOT
  suffix: jar
      #部署多台服务器 必须包含ip 端口 账号 密码 逗号分隔
  ip: 192.168.101.130,192.168.101.131
  port: 22,22
  username: root,root
  password: root,root
  
