#部署目录
deploy:
  location: /Users/zhaoyong/Documents/workspace/www.oner365.com/cloud/dna-cloud
  name: /Users/zhaoyong/Documents/deploy
  version: 1.0.0-SNAPSHOT
  suffix: jar
  project: bazl-dna-eureka,bazl-dna-config,bazl-dna-zuul,bazl-dna-files,bazl-dna-turbine,bazl-dna-zipkin,bazl-dna-system,bazl-dna-gateway,bazl-dna-elasticsearch,bazl-dna-monitor,bazl-dna-kafka,bazl-dna-websocket,bazl-dna-generator,bazl-dna-elasticsearch
  lib: bazl-dna-common

#服务器配置  
servers:
  deploy: true
  name: /usr/local/tomcat/dnacloud
  ip: 192.168.101.130,192.168.101.131
  port: 22,22
  username: root,root
  password: root,root